# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build_test:
        runs-on: ubuntu-latest

        steps:
            - name: Repo Checkout
              uses: actions/checkout@v4
            - name: Use Node 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install node modules
              run: npm install
            - name: Execute security tests
              run: npm audit fix --force
            - name: Run Tests
              run: npm test
